#!/bin/bash

# create an OvS bridge called diamond_city
sudo ovs-vsctl add-br diamond_city


# create network namespaces
sudo ip netns add wario &> /dev/null
sudo ip netns add yoshi &> /dev/null

# create bridge internal interface
sudo ovs-vsctl add-port diamond_city wario -- set interface wario type=internal


# plug the OvS bridge internals into the peach and bowser namespaces
sudo ip link set wario netns wario


# bring interface UP in bowser and peach
sudo ip netns exec wario ip link set dev wario up


# add IP address to interface
sudo ip netns exec wario ip addr add 10.64.0.10/24 dev wario


#!/bin/bash

# create an OvS bridge called yoshi-island
sudo ovs-vsctl add-br yoshi-island

# create network namespace
sudo ip netns add yoshi &> /dev/null

# create VETH
sudo ip link add yoshi2net type veth peer name net2yoshi &> /dev/null

# plug in VETH to namespace
sudo ip link set yoshi2net netns yoshi &> /dev/null

# add IP address assignments
sudo ip netns exec yoshi ip a add 10.64.0.11/24 dev yoshi2net &> /dev/null

# make all connections UP
sudo ip netns exec yoshi ip link set dev yoshi2net up &> /dev/null
sudo ip netns exec yoshi ip link set dev lo up &> /dev/null

# add patch port
sudo ovs-vsctl add-port yoshi-island net2yoshi
sudo ovs-vsctl add-port diamond-city toad -- set interface toad type=patch options:peer=metalwario


sudo ovs-vsctl add-port yoshi-island  metalwario -- set interface metalwario type=patch options:peer=toad

ping

sudo ip netns exec wario ping -c 1 10.64.0.11
